# Generated by Django 4.0.4 on 2022-06-13 10:18

from django.db import migrations, models
import django.db.models.deletion
import id_capture.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.ImageField(upload_to=id_capture.models.get_id_card_path)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'nam'), ('F', 'nu')], default=None, max_length=1, null=True)),
                ('class_year', models.CharField(max_length=15)),
                ('major', models.CharField(choices=[('công nghệ thông tin', 'Công nghệ thông tin'), ('khoa học máy tính', 'Khoa học máy tính'), ('máy tính và robot', 'Máy tính và robot'), ('cơ kỹ thuật', 'Cơ kỹ thuật'), ('công nghệ kỹ thuật xây dựng', 'Công nghệ kỹ thuật xây dựng'), ('công nghệ Hàng không vũ trụ', 'Công nghệ Hàng không vũ trụ'), ('kỹ thuật điều khiển và tự động hóa', 'Kỹ thuật điều khiển và tự động hóa'), ('công nghệ nông nghiệp', 'Công nghệ nông nghiệp')], max_length=50)),
                ('face_image', models.BooleanField(default=False)),
                ('id_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='id_capture.idcard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='id_capture.student')),
                ('image', models.ImageField(blank=True, null=True, upload_to=id_capture.models.get_face_image_path)),
            ],
        ),
    ]
