# Generated by Django 4.0.2 on 2022-03-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], default=None, max_length=1, null=True)),
                ('class_year', models.CharField(max_length=15)),
                ('major', models.CharField(max_length=10)),
                ('id_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
            ],
        ),
    ]
