# Generated by Django 4.0.2 on 2022-03-18 03:37

from django.db import migrations, models
import id_capture.models


class Migration(migrations.Migration):

    dependencies = [
        ('id_capture', '0002_alter_student_id_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to=id_capture.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
