# Generated by Django 4.0.3 on 2022-03-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_capture', '0003_alter_student_id_image_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(choices=[('công nghệ thông tin', 'Công nghệ thông tin'), ('khoa học máy tính', 'Khoa học máy tính'), ('máy tính và robot', 'Máy tính và robot'), ('cơ kỹ thuật', 'Cơ kỹ thuật'), ('công nghệ kỹ thuật xây dựng', 'Công nghệ kỹ thuật xây dựng'), ('công nghệ Hàng không vũ trụ', 'Công nghệ Hàng không vũ trụ'), ('kỹ thuật điều khiển và tự động hóa', 'Kỹ thuật điều khiển và tự động hóa'), ('công nghệ nông nghiệp', 'Công nghệ nông nghiệp')], max_length=50),
        ),
    ]
